Iter9
xChygyNx/metrical pull request #10
Opened 2024-12-26 09:32 UTC by xChygyNx

2024-12-27 20:18 UTC, s-shpak requested changes

2024-12-27 20:18 UTC, s-shpak commented on internal/agent/compress.go
> +		err = fmt.Errorf("error in gzip compress data: %w", err)
Если эта ошибка не критическая, то ее надо залогировать и продолжить выполнение программы.

А если критическая (кажется, что да), то надо после нее завершить обработку запроса

2024-12-27 20:18 UTC, s-shpak commented on internal/server/config.go
> +	config := new(Config)
Так более идиоматично:

```suggestion
	config := &Config{}
```

2024-12-27 20:18 UTC, s-shpak commented on internal/server/fileMemStorage.go
> +	dirPath, err := filepath.Abs("./memory_metrics")
Зачем здесь эта константа ? Кажется, что из-за нее не проходят автотесты, т.к. не могут найти файла, который создается, по тому адресу, который передан флагом

2024-12-27 20:18 UTC, s-shpak commented on internal/server/fileMemStorage.go
> +	if _, err = os.Stat(storageFilePath); err != nil {
Вызов этой функции для проверки существования файла не имеет смысла: во время вызова файл может существовать, а сразу после быть удален, так что попытка записи или чтения не будут иметь смысла.

Работай с файлом напрямую, а возвращаемые ошибки будут индикаторами существования файла.

2024-12-27 20:18 UTC, s-shpak commented on internal/server/handlers.go
> +			http.Error(res, errorMsg, http.StatusBadRequest)
Почему это `BadRequest` ? Кажется, что это внутренняя ошибка сервиса

2024-12-27 20:18 UTC, s-shpak commented on internal/server/handlers.go
> +		log.Println("hi from update")
Поубирай эти сообщения, которые остались после дебаггинга на 1-1

2024-12-27 20:18 UTC, s-shpak commented on internal/server/handlers.go
> +			log.Println(errorMsg)
Штатные ошибки не надо логировать.

Кроме того, если ты используешь кастомный логгер, то не используй log в коде. Его использование оправдано только если ты логируешь что-то до инициализации кастомного логгера.

2024-12-27 20:18 UTC, s-shpak commented on internal/server/handlers.go
> +			http.Error(res, errorMsg, http.StatusInternalServerError)
В случае `InternalServerError` пользователю нельзя отдавать сообщение с ошибкой -- это проблема для безопасности сервиса

2024-12-27 20:18 UTC, s-shpak commented on internal/server/routing.go
> +var sugar zap.SugaredLogger
Я не советую использовать глобальный логгер. Такая практика встречается, но я предлагаю не использовать ее в курсе.

Единственный аргумент для использования глобального логгера -- возможность не передавать его напрямую в компоненты, где он используется. При этом использование глобального логгера несет в себе все минусы глобальных переменных, а также минусы самого глобального логгера.

Можно выделить две основные проблемы "глобального" подхода: 

1. Теперь ты не можешь кастомизировать логгер для конкретного компонента, в котором он используется. Например, если логгер явным образом передается в компонент при его инициализации, то ты можешь настроить его так, чтобы к каждому сообщению добавлялось поле с именем компонента, который это сообщение сгенерировал. Вобщем, локальные логгеры кастомизируются легко, глобальные -- сложно.

2. С одной стороны, удобно, что логгер не надо явным образом передавать в компонент. С другой, теперь мы создаем неявные зависимости: поведение компонента зависит от логгера (если, например, логгер не будет корректно проинициализирован, то компонент тоже поломается, т.к. при вызове логгера будет падать). Неявные зависимости хуже чем явные. Потому с моей т.з. передавать логгер явным образом как аргумент функции, или как поле объекта -- лучше, чем спрятать его в глобальную переменную

2024-12-27 20:18 UTC, s-shpak commented on internal/server/routing.go
> +		middlewareLogger(GzipHandler(SaveMetricHandle(storage, syncInfo)), sugar))
Middleware необходимо регистрировать при помощи https://pkg.go.dev/github.com/go-chi/chi#Mux.Use

2024-12-27 20:18 UTC, s-shpak commented on internal/server/types/httpTypes.go
> +		err = fmt.Errorf("error in close of gzipWriter.Writer: %w", err)
Почему не

```suggestion
		return fmt.Errorf("error in close of gzipWriter.Writer: %w", err)
```

?

2025-01-03 03:32 UTC, xChygyNx commented on internal/server/handlers.go
> +			http.Error(res, errorMsg, http.StatusInternalServerError)
я же правильно понимаю, что ее надо залогировать? просто в предыдущей ошибке говорил, что и логировать не надо

2025-01-04 11:40 UTC, s-shpak commented on internal/server/handlers.go
> +			http.Error(res, errorMsg, http.StatusInternalServerError)
Да, внутреннюю ошибку сервиса надо залогировать -- это поможет разработчику обнаружить и исправить ее. Штатные ошибки (произошедшие по вине клиента) логировать не надо

2025-01-04 15:23 UTC, xChygyNx commented on internal/server/routing.go
> +		middlewareLogger(GzipHandler(SaveMetricHandle(storage, syncInfo)), sugar))
а я же сделал, или сделал что то не то?
https://github.com/xChygyNx/metrical/blob/iter9/internal/server/routing.go#L85

2025-01-04 15:45 UTC, xChygyNx commented on internal/server/handlers.go
> +			http.Error(res, errorMsg, http.StatusInternalServerError)
сейчас у меня везде на StatusInternalServerError работает такая конструкция
```
    errorMsg := fmt.Errorf("Occur some error: %w", err).Error()
    fmt.Println(errorMsg)
    http.Error(res, internalServerErrorMsg, http.StatusInternalServerError)
    return
```
а на StatusNotFound и StatusBadRequest такая
```
    errorMsg := fmt.Errorf("failed to write metrics in file: %w", err).Error()
    http.Error(res, errorMsg, http.StatusBadRequest)
    return
```

2025-01-12 11:44 UTC, merged