Iter5
xChygyNx/metrical pull request #6
Opened 2024-12-01 20:13 UTC by xChygyNx

2024-12-04 19:47 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-12-04 19:47 UTC, s-shpak commented on cmd/agent/main.go
> +		if time.Now().After(timeReport.Add(time.Duration(config.reportInterval) * time.Second)) {
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-12-04 19:47 UTC, s-shpak commented on cmd/agent/main.go
> +				fmt.Println(err)
Не используй пакет `fmt` для логгирования, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-12-04 19:47 UTC, s-shpak commented on cmd/agent/senders.go
> +		body, _ := io.ReadAll(resp.Body)
Ошибки нужно проверять

2024-12-04 19:47 UTC, s-shpak commented on cmd/server/handlers.go
> +	match, err := regexp.MatchString(`^\/update\/(gauge|counter)`, path)
Зачем эта проверка ? Автотесты без нее не проходят ?

2024-12-04 19:47 UTC, s-shpak commented on cmd/server/handlers.go
> +		http.Error(res, "Internal Server error", http.StatusInternalServerError)
Ошибки 5** нужно логировать

2024-12-04 19:47 UTC, s-shpak commented on cmd/server/handlers.go
> +	match, err := regexp.MatchString(`^\/value\/(gauge|counter)`, path)
Мне кажется, что эти проверки не нужны

2024-12-04 19:47 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Паниковать не надо: используй `log.Fatal` для:
    1. вывода ошибки
    2. завершения процесса с ошибкой

2024-12-04 19:47 UTC, s-shpak commented on cmd/server/types.go
> +var instance *memStorage
Не используй глобальные переменные. Ты можешь создавать объект, наполнять его и передавать туда, где он будет использоваться

2024-12-04 19:47 UTC, s-shpak commented on cmd/agent/config.go
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`. Причем разнеси функционал в `internal` на разные пакеты

2024-12-08 11:48 UTC, xChygyNx commented on cmd/server/handlers.go
> +	match, err := regexp.MatchString(`^\/value\/(gauge|counter)`, path)
А мне кажется без них никак. В chi  задан роутинг `"/update/{mType}/{metric}/{value}"` для сервера и `/value/{mType}/{metric}` для агента, то есть в эти хэндлеры можно попасть и по пути `http://value/something/strange`, и именно эти проверки отсекают такие запросы и в соответствии с тз возвращают статусы 400 или 404

2024-12-08 13:26 UTC, xChygyNx commented on cmd/agent/flags.go
> +func (hp *HostPort) Set(value string) error {
Проверил по программе отсюда https://golangbyexample.com/parse-url-golang/. Если закидывать в  url.Parse строку вида "<host>:<port>" без схем, пользователей паролей и прочей мишуры,  как этот адрес будет задан во флаге или переменной окружения, то в вернувшейся структуре хост будет лежать в поле Schema, а порт в поле Opaque, что на мой взгляд очень нелогично и затруднит дальнейшую поддержку кода

2024-12-08 18:44 UTC, xChygyNx commented on cmd/server/handlers.go
> +		http.Error(res, "Internal Server error", http.StatusInternalServerError)
не оч понял что такое ошибки 5**, но залогировал ошибки перед http.Error

2024-12-09 07:26 UTC, xChygyNx commented on cmd/server/types.go
> +var instance *memStorage
Не знал как передать дополнительный параметр в  http.HandleFunc. Позже увидел решение проблемы в обсуждениях в пачке

2024-12-09 14:03 UTC, s-shpak commented on internal/server/handlers.go
> +			log.Println("Unknown metric type, must be gauge or counter")
Ошибки которые приводят к статус-коду, который начинается с цифры 4 (400, 401, ...) я называю ошибками 4**. Это штатные ошибки: клиент неправильно обратился к нашему сервису, наш сервис корректно обработал ошибку и вернул ее пользоавтелю. Такие ошибки логировать не надо -- информация о них не дает нам никаких новых данных

С другой стороны ошибки 5** -- те, которые приводят к статус коду, начинающемуся с 5 (500, 501, ...), -- необходимо логировать, т.к. это внутрениие ошибки сервиса, и возникли, потому что сервис столкнулся с неожиданной проблемой. Информацию о них не надо передавать пользователю, т.к. это проблема безопасности

2024-12-09 14:03 UTC, s-shpak commented on cmd/server/handlers.go
> +	match, err := regexp.MatchString(`^\/value\/(gauge|counter)`, path)
Это твое внутреннее ощущение, или оно чем-то подкреплено ? У этих путей разные префиксы, как на уровне роутинга может возникнуть конфликт ?

2024-12-09 14:06 UTC, s-shpak requested changes

2024-12-09 20:18 UTC, xChygyNx commented on internal/server/handlers.go
> +			log.Printf("Got value with type %T", valueType)
без этого логирования go vet выдает ошибку
```
assigning the result of this type assertion to a variable (switch valueInterface := valueInterface.(type)) could eliminate type assertions in switch cases
```
то есть приведение типа интерфейса я должен назначить какой-то переменной. Ничего умнее чем залогировать ее тип я не придумал, а что-то с ней делать надо, иначе компилятор ругается

2024-12-10 18:14 UTC, xChygyNx commented on cmd/server/handlers.go
> +	match, err := regexp.MatchString(`^\/value\/(gauge|counter)`, path)
Переписал на получение значений из http.Request.PathValues

2024-12-10 20:30 UTC, s-shpak requested changes

2024-12-10 20:30 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
Ты добавил конфигурацию неправильно. Пожалуйста, внимательно прочитай инструкции здесь: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-12-10 20:30 UTC, s-shpak commented on internal/server/handlers.go
> +			errorMsg := fmt.Sprintf("Incorrect metric name, must contains only from alphabetical "+
А откуда это требование ? Его нет в ТЗ, потому лучше не усложнять код

2024-12-11 04:58 UTC, xChygyNx commented on internal/server/handlers.go
> +			errorMsg := fmt.Sprintf("Incorrect metric name, must contains only from alphabetical "+
к предыдущему замечанию по поводу линтера, не смог к нему коммент приделать
Вроде все сделал как там, на всякий случай сделал еще раз

2024-12-11 07:36 UTC, xChygyNx commented on .github/workflows/golangci-lint.yml
к предыдущему замечанию по поводу линтера, не смог к нему коммент приделать
Вроде все сделал как там, на всякий случай сделал еще раз

2024-12-11 10:19 UTC, s-shpak commented on .github/workflows/golangci-lint.yml
Смотри, для настройки линтера используется два файла. Один -- с конфигурацией линтера, https://github.com/s-shpak/praktikum-golangci-lint/blob/main/.golangci.yml -- кладется в корень репозитория (рядом с `go.mod`). Второй -- для настройки Github Actions, https://github.com/s-shpak/praktikum-golangci-lint/blob/main/workflows/golangci-lint.yml -- кладется в `workflows/`.

Второй ты уже добавил, теперь надо добавить первый.

2024-12-11 10:24 UTC, s-shpak requested changes
См. комментарий

2024-12-11 19:44 UTC, xChygyNx commented on .github/workflows/golangci-lint.yml
понял, он у меня на локалке лежит, просто не проиндексирован git'ом, вот и не закидывается в репозиторий))

2024-12-12 19:18 UTC, s-shpak approved these changes

2024-12-12 20:22 UTC, merged